### ISSUE TITLE
K- Nuclear Yield In Kilotons

### ISSUE THREAD

**Issue by carlocorradini** [orbat-mapper/convert-symbology#11]
`SYMBOL_MODIFIER_MAP` does not define any entry for `K-` (_Nuclear Yield In Kilotons_).
Is this the proper behaviour or?

**Comment by kjellmf** [comment]
I could not find any `K-` entries in MILSTD 2525C. Is this from an older version of the standard?

**Comment by carlocorradini** [comment]
Yeah I've seen it in APP6A.
Maybe it has been deprecated/removed?

**Comment by kjellmf** [comment]
> Yeah I've seen it in APP6A. Maybe it has been deprecated/removed?

I could not find information about this in the newest versions of the standards or MILSTD 2525C, so it has probably been removed. If a mapping makes sense I can add it, but then I need to find the mappings first.

**Comment by carlocorradini** [comment]
See http://www.mapsymbs.com/APP-6ADRDCValcartierEdition121(Mod).pdf
Page **111**.
I don't know if you want to add the mapping: "K-" -> "000" or another number symbol

**Comment by kjellmf** [comment]
Thank you @carlocorradini for the link to the document. In footnote 69 on that page it is stated that  "Mil-Std-2525B Change Proposal Mil01-02 deletes this Symbol ID code from the table."  That explains why I can't find it in newer versions. 

I'll update the mapping. If I can't find a suitable number symbol I will probably just add a note or use `000`.
