### ISSUE TITLE
Missing Symbol ID

### ISSUE THREAD

**Issue by carlocorradini** [orbat-mapper/convert-symbology#12]
Reading through APP6B pages 106/107 (https://web.archive.org/web/20141018015705/http://armawiki.zumorc.de/files/NATO/APP-06(B)%20Joint%20Symbology.pdf) I've discovered additional symbols that are not present in the mapping:

- `M-` | Mobility Equipment
- `MF` | Mobility Equipment Fixed Wing
- `MH` | Mobility Equipment Helicopter
- `MM` | Mobility Equipment Missile
- `S-` | Mobility Space

Even though these symbols are not present in `APP6D`, I believe we should map them to the closest match possible (e.g., `MM` -> `M-`).

PS: Note that this issue is related to #11

**Comment by kjellmf** [comment]
I have now added the mappings, but because they don't exists in newer versions of the standards they are just mapped to `000`. This is what I do by default if I can't find a mapping.
