### ISSUE TITLE
Is it possible to convert Tactical Graphics codes?

### ISSUE THREAD

**Issue by nebsar** [orbat-mapper/convert-symbology#5]

**Comment by kjellmf** [comment]
I have to admit that I have not tested this, but the library should support this. If not it is a bug.

**Comment by kjellmf** [comment]
I've added a few tests in 3aabeaeeb5bc91f69a6a17e6d1dd6e5b128fe515 and 4b5f3cee091b1e214436393d3c5513874932e818 to confirm that the library can convert tactical graphics codes. They passed, so the answer is yes.

**Comment by nebsar** [comment]
Sorry I should have asked this question in the discussion section. But I tried some of the conversions in the orbat-mapper application and it did not work. I will let you know which ones didn't work. Is orbat-mapper using the same conversion library?

**Comment by kjellmf** [comment]
No worries. I added the discussion section after you opened the issue.
orbat-mapper uses the same library, but it does not yet support multi-point
tactical graphics. That is probably why it didn't work. It should show the
converted code though with a question mark symbol.

**Comment by nebsar** [comment]
It should have shown the converted code, however it could not. Most probably the Tactical Graphics SIDC that I tested for conversion is not mapped in the conversion library.

**Comment by kjellmf** [comment]
If you share the missing SIDCs I'll add them to the library. The conversion
from number SIDCs to letter SIDCs has not been tested thoroughly, so there
may be some bugs as well.

**Comment by nebsar** [comment]
These are some of them. I do not know may be these are parent of other child SIDCs and because of that they do not work. For example, when I enter G-M-OWC-------X, conversion does not work but when I enter G-M-OWCS------X, it works.  There may be more. 
Additionally, it converts G-M-OWU-------X to 102500002903010000 but, does not convert 102500002903010000 to G-M-OWU-------X

G-M-OW--------X
G-M-OWC-------X
G-M-OH--------X
G-M-OHT-------X
G-M-B---------X
G-M-BC--------X
G-M-BD--------X

**Comment by kjellmf** [comment]
`G-M-OWU-------X` is a bug. The other ones fail because they don't actually have a graphic and are used just for hierarchical purposes. I should probably pick the closest one instead.

**Comment by kjellmf** [comment]
I have pushed some fixes in 6693513b152e31ab528073db4835318b2ad4355c and 2b452ac3cecf4daeab8cc5f2980bd045e9acbe7. The library will now try to pick the closest symbol it can find. Not pushed to NPM yet. I'll do that when #8 and #7 is closed.

**Comment by kjellmf** [comment]
Version 1.0.0 is now available on NPM.
