### ISSUE TITLE
MW | Pack Animals should be 037 and not 047

### ISSUE THREAD

**Issue by carlocorradini** [orbat-mapper/convert-symbology#9]
`MV` (_Pack Animals_) should be `037` (_Not Applicable | Equipment Mobility On Land | Pack Animals_) and not `047` (_Not Applicable | Equipment Mobility On Snow | Reserved For Future Use_):

https://github.com/orbat-mapper/convert-symbology/blob/88d6e36f487282e3f97cc9d41a871830c82bded8/lib/mappings.ts#L164

**Comment by kjellmf** [comment]
Thank you for the bug report. Merged now.
